"""Stage 3 diagnostic soak (owned by S3-SOAK-001).

Runs one canonical single-world 300-index scenario through HTTP
with scripted fakes, mirroring the S2 gate, and records growth
numbers every later Stage 3 lane designs against. No new
features; this lane reports, it does not gate.

The recall probe rides a communicate intent, not a resolver
effect: resolver effect facts feed narration, never observation
or memory rows, so only intent-derived content (attempt facts,
memory summaries) enters context assembly. Wren tells Ash the
probe topic in the opening phases; the audit checks whether
Wren's day-29 assembly still surfaces the resulting memory.

Evidence (regenerated by this test, gitignored):
``evidence/stage3-soak-v1/`` with scenario, growth, tables,
recall, and README files.
"""

from __future__ import annotations

import asyncio
import json
import time
from collections.abc import Iterator
from pathlib import Path
from typing import Any
from uuid import UUID

import pytest
from fastapi.testclient import TestClient
from test_stage1_api import ApiClient

from worldsim.application.orchestration.service import derive_run_id
from worldsim.infrastructure.db.engine import create_engine
from worldsim.infrastructure.model_gateway.fake import FakeGateway
from worldsim.infrastructure.model_gateway.profiles import FAKE_TEST_PROFILE
from worldsim.infrastructure.repositories.unit_of_work import create_unit_of_work
from worldsim.infrastructure.settings import Settings
from worldsim.interfaces.http.app import create_app

ROOT = Path(__file__).parent.parent.parent
SEED_DIR = ROOT / "content" / "seeds" / "stage0"
MIGRATIONS = ROOT / "backend" / "migrations"
EVIDENCE = ROOT / "evidence" / "stage3-soak-v1"

WORLD_ID = UUID("10000000-0000-4000-8000-000000000001")
WREN_ID = UUID("10000000-0000-4000-8000-000000000101")
ASH_ID = UUID("10000000-0000-4000-8000-000000000102")
PLACEHOLDER_SNAPSHOT = "00000000-0000-4000-8000-000000000000"
PROBE_TEXT = "the north bridge is cursed"
PHASES = 300

_ROLE_MARKERS = (
    ("decide", "You decide"),
    ("react", "You react"),
    ("resolve", "You resolve"),
    ("narrate", "You narrate"),
    ("direct", "You direct"),
    ("summarize", "You summar"),
)


@pytest.fixture
def soak(migrated_db: None) -> Iterator[tuple[ApiClient, FakeGateway]]:
    gateway = FakeGateway(profile=FAKE_TEST_PROFILE)
    app = create_app(
        Settings(),
        seed_dir=SEED_DIR,
        migrations_dir=MIGRATIONS,
        gateway_factory=lambda: gateway,
    )
    with TestClient(app) as raw:
        yield ApiClient(raw), gateway


def _wait_json(actor: UUID) -> str:
    return json.dumps(
        {"family": "wait", "character_id": str(actor), "snapshot_id": PLACEHOLDER_SNAPSHOT}
    )


def _role_of(system: str) -> str:
    for role, marker in _ROLE_MARKERS:
        if marker in system:
            return role
    return "unmatched"


def _route_for() -> Any:
    narrator_calls = {"n": 0}
    decide_calls = {"n": 0}

    def _route(request: Any) -> str | None:
        prompt, system = request.prompt, request.system or ""
        if "You decide" in system:
            if "Wren" in prompt:
                decide_calls["n"] += 1
                if decide_calls["n"] <= 1:
                    return json.dumps(
                        {
                            "family": "communicate",
                            "character_id": str(WREN_ID),
                            "snapshot_id": PLACEHOLDER_SNAPSHOT,
                            "target_character_id": str(ASH_ID),
                            "topic": PROBE_TEXT,
                        }
                    )
                return _wait_json(WREN_ID)
            return _wait_json(ASH_ID)
        if "You react" in system:
            if "Wren" in prompt:
                return json.dumps(
                    {
                        "family": "observe",
                        "character_id": str(WREN_ID),
                        "snapshot_id": PLACEHOLDER_SNAPSHOT,
                        "focus": "Ash",
                    }
                )
            return _wait_json(ASH_ID)
        if "You resolve" in system:
            return json.dumps(
                {
                    "outcome": "success",
                    "effects": [
                        {
                            "schema_version": 1,
                            "affected_ids": [str(WREN_ID)],
                            "expected_versions": {str(WREN_ID): 0},
                            "effect_type": "record_observation",
                            "observer_character_id": str(WREN_ID),
                            "facts": [{"key": "day", "value": "passing"}],
                        }
                    ],
                    "rationale": "The day passes quietly.",
                }
            )
        if "You narrate" in system:
            narrator_calls["n"] += 1
            recruit = "\nRECRUIT[Lyra]: elf ranger, level 3" if narrator_calls["n"] <= 6 else ""
            return json.dumps(
                [{"text": f"The phase passes.{recruit}", "cited_fact_keys": ["attempt:wait"]}]
            )
        if "You direct" in system:
            return json.dumps({"action": "noop", "reason": "calm stretch"})
        if "You summar" in system:
            return json.dumps({"text": "A quiet day.", "source_ids": []})
        return None

    return _route


def test_thirty_day_soak(soak: tuple[ApiClient, FakeGateway]) -> None:
    client, gateway = soak
    gateway.route = _route_for()
    headers = {"X-Worldsim-Role": "watcher"}
    started = time.perf_counter()

    seeded = client.post("/api/v1/world/seed", headers=headers)
    assert seeded.status_code == 200, seeded.text

    begun = client.post(
        "/api/v1/stage1/party/begin",
        json={
            "world_id": str(WORLD_ID),
            "name": "Borin",
            "race": "dwarf",
            "character_class": "fighter",
            "level": 1,
        },
        headers=headers,
    )
    assert begun.status_code == 200, begun.text

    phase_seconds: dict[int, float] = {}
    phase_bytes: dict[int, dict[str, int]] = {}
    tables: dict[str, dict[str, int]] = {}
    for index in range(1, PHASES + 1):
        sent_before = len(gateway.sent_requests)
        phase_start = time.perf_counter()
        response = client.post(
            "/api/v1/stage1/advance",
            json={"world_id": str(WORLD_ID), "absolute_index": index},
            headers=headers,
        )
        assert response.status_code == 200, response.text
        phase_seconds[index] = round(time.perf_counter() - phase_start, 3)
        phase_bytes[index] = _bytes_for(gateway.sent_requests[sent_before:])
        if index % 10 == 0:
            tables[str(index)] = asyncio.run(_sample_tables())

    wall_seconds = round(time.perf_counter() - started, 1)
    _write_evidence(phase_seconds, phase_bytes, tables, wall_seconds)


def _bytes_for(requests: list[Any]) -> dict[str, int]:
    per_role: dict[str, int] = {}
    for request in requests:
        role = _role_of(request.system or "")
        size = len(request.prompt) + len(request.system or "")
        per_role[role] = per_role.get(role, 0) + size
    return per_role


async def _sample_tables() -> dict[str, int]:
    engine = create_engine(Settings())
    try:
        async with create_unit_of_work(engine) as uow:
            return {
                "events": await uow.events.count_events(WORLD_ID),
                "obs_wren": len(await uow.perception.observations_for_observer(WREN_ID, 100000)),
                "obs_ash": len(await uow.perception.observations_for_observer(ASH_ID, 100000)),
                "mem_wren": len(await uow.perception.memories_for_owner(WREN_ID)),
                "mem_ash": len(await uow.perception.memories_for_owner(ASH_ID)),
                "characters": len(await uow.characters.list_for_world(WORLD_ID)),
                "hooks": await uow.narrative.count_active_hooks(WORLD_ID),
                "arcs": await uow.narrative.count_active_arcs(WORLD_ID),
            }
    finally:
        await engine.dispose()


def _write_evidence(
    phase_seconds: dict[int, float],
    phase_bytes: dict[int, dict[str, int]],
    tables: dict[str, dict[str, int]],
    wall_seconds: float,
) -> None:
    async def _audit() -> dict[str, Any]:
        engine = create_engine(Settings())
        try:
            async with create_unit_of_work(engine) as uow:
                per_phase: dict[str, dict[str, Any]] = {}
                manifest_samples: dict[str, Any] = {}
                for index in range(1, PHASES + 1):
                    run = await uow.phases.get_run(derive_run_id(WORLD_ID, index))
                    assert run.state.value == "completed"
                    calls = await uow.traces.list_for_phase_run(run.id)
                    tokens: dict[str, int] = {}
                    for call in calls:
                        tokens[call.role] = tokens.get(call.role, 0) + (
                            call.prompt_tokens + call.completion_tokens
                        )
                    per_phase[str(index)] = {
                        "model_calls": len(calls),
                        "tokens": tokens,
                        "prompt_bytes": phase_bytes[index],
                    }
                    if index % 10 == 0:
                        excluded: dict[str, int] = {}
                        included = 0
                        for call in calls:
                            try:
                                manifest = await uow.traces.get_manifest(call.id)
                            except Exception:
                                continue
                            for source in manifest.sources:
                                if source.reason == "permitted":
                                    included += 1
                                else:
                                    key = f"{source.kind}:{source.reason}"
                                    excluded[key] = excluded.get(key, 0) + 1
                        manifest_samples[str(index)] = {
                            "included": included,
                            "excluded": sum(excluded.values()),
                            "excluded_by_reason": excluded,
                        }
                probe_source = await _find_probe(uow)
                recall = await _recall_verdict(uow, probe_source)
                world = await uow.worlds.get(WORLD_ID)
                return {
                    "per_phase": per_phase,
                    "manifest_samples": manifest_samples,
                    "probe_source": probe_source,
                    "recall": recall,
                    "day": world.day,
                }
        finally:
            await engine.dispose()

    findings = asyncio.run(_audit())
    assert findings["day"] == 31, findings["day"]

    times = sorted(phase_seconds.values())
    p50 = times[len(times) // 2]
    p95 = times[int(len(times) * 0.95)]
    day1_bytes = _phase_size(findings["per_phase"]["1"])
    day30_bytes = _phase_size(findings["per_phase"]["300"])
    last_tables = tables["300"]
    first_tables = tables["10"]
    fastest = max(last_tables, key=lambda k: last_tables[k] - first_tables.get(k, 0))

    EVIDENCE.mkdir(parents=True, exist_ok=True)
    scenario = {
        "scenario": "stage3-soak-v1",
        "world_id": str(WORLD_ID),
        "phases": PHASES,
        "wall_seconds": wall_seconds,
        "size_unit": "prompt bytes (prompt+system characters) per role from "
        "sent fake-gateway requests; model-reported tokens stay 0 on fakes",
    }
    growth = {
        "per_phase": findings["per_phase"],
        "manifest_samples": findings["manifest_samples"],
    }
    recall = {
        "probe_text": PROBE_TEXT,
        "probe_source": findings["probe_source"],
        "day29_verdict": findings["recall"],
        "note": "Probe planted by Wren's opening communicate intents; "
        "verdict scanned over day-29 manifests, baseline over phases 3-5.",
    }
    for name, payload in [
        ("scenario", scenario),
        ("growth", growth),
        ("tables", tables),
        ("recall", recall),
    ]:
        (EVIDENCE / f"{name}.json").write_text(json.dumps(payload, indent=2) + "\n")

    fastest_growth = last_tables[fastest] - first_tables.get(fastest, 0)
    (EVIDENCE / "README.md").write_text(
        "# Stage 3 soak report: stage3-soak-v1\n\n"
        "Diagnostic only: no thresholds, no gates. Later lanes design\n"
        "against these numbers.\n\n"
        f"- Prompt bytes day 1 vs day 30: {day1_bytes} vs {day30_bytes}\n"
        f"- Phase seconds p50/p95: {p50}s / {p95}s over {PHASES} phases\n"
        f"- Fastest-growing table: {fastest} "
        f"(+{fastest_growth} rows from phase 10 to phase 300)\n"
        f"- Recall probe: {findings['recall']['verdict']}\n"
        f"- Wall seconds: {wall_seconds}\n"
    )


def _phase_size(entry: dict[str, Any]) -> int:
    return sum(entry["prompt_bytes"].values())


async def _find_probe(uow: Any) -> str | None:
    memories = await uow.perception.memories_for_owner(WREN_ID)
    for memory in memories:
        if PROBE_TEXT in memory.text:
            return f"mem:{memory.id}"
    return None


async def _scan_manifests(uow: Any, start: int, end: int, probe_source: str) -> dict[str, int]:
    reasons: dict[str, int] = {}
    for index in range(start, end + 1):
        run = await uow.phases.get_run(derive_run_id(WORLD_ID, index))
        for call in await uow.traces.list_for_phase_run(run.id):
            try:
                manifest = await uow.traces.get_manifest(call.id)
            except Exception:
                continue
            for source in manifest.sources:
                if source.source_id == probe_source:
                    reasons[source.reason] = reasons.get(source.reason, 0) + 1
    return reasons


async def _recall_verdict(uow: Any, probe_source: str | None) -> dict[str, Any]:
    if probe_source is None:
        return {"verdict": "absent", "detail": "probe memory never recorded"}
    baseline = await _scan_manifests(uow, 3, 5, probe_source)
    reasons = await _scan_manifests(uow, 281, 290, probe_source)
    if not reasons:
        return {
            "verdict": "absent",
            "detail": "probe source in no day-29 manifest",
            "baseline": baseline,
        }
    if reasons.get("permitted"):
        return {"verdict": "included", "reasons": reasons, "baseline": baseline}
    if any("budget" in reason for reason in reasons):
        return {"verdict": "excluded-by-budget", "reasons": reasons, "baseline": baseline}
    return {"verdict": "excluded", "reasons": reasons, "baseline": baseline}
