"""Repository ports for Stage 0 aggregates (owned by S0-UOW-001).

Adapters return domain models, never ORM objects. Every mutating save
compares an expected optimistic version and bumps on success.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from worldsim.domain.characters import Character, CharacterCard
from worldsim.domain.events import CommittedEffect, WorldEvent
from worldsim.domain.narration import NarrationBeat
from worldsim.domain.party import PartyMember
from worldsim.domain.perception import Observation, RecentMemory
from worldsim.domain.phases import PhaseRun, PhaseSnapshot
from worldsim.domain.rules.dnd import Sheet
from worldsim.domain.scenes import Attempt, Intent, Reaction, Resolution, Scene
from worldsim.domain.tasks import Lease, OutboxMessage, TaskRun
from worldsim.domain.world import Location, World


def canonical_order(ids: list[UUID]) -> list[UUID]:
    """Deterministic lock order: every transaction locks shared aggregates
    cheapest-first by ID hex, so two writers cannot deadlock."""
    return sorted(set(ids), key=lambda item: item.hex)


class WorldRepository(Protocol):
    async def get(self, world_id: UUID) -> World: ...
    async def list_worlds(self) -> list[World]: ...
    async def add(self, world: World) -> None: ...
    async def save(self, world: World, expected_version: int) -> World: ...
    async def get_clock(self, world_id: UUID) -> tuple[int, str, int]: ...
    async def set_clock(
        self, world_id: UUID, day: int, phase: str, absolute_index: int
    ) -> None: ...
    async def get_config(self, world_id: UUID) -> dict[str, object]: ...
    async def put_config(self, world_id: UUID, key: str, value: object) -> None: ...


class LocationRepository(Protocol):
    async def get(self, location_id: UUID) -> Location: ...
    async def list_for_world(self, world_id: UUID) -> list[Location]: ...
    async def add(self, location: Location) -> None: ...
    async def save(self, location: Location, expected_version: int) -> Location: ...


class CharacterRepository(Protocol):
    async def get(self, character_id: UUID) -> Character: ...
    async def list_for_world(self, world_id: UUID) -> list[Character]: ...
    async def add_identity(self, character_id: UUID, world_id: UUID, name: str) -> None: ...
    async def add_card(self, card: CharacterCard) -> None: ...
    async def get_card(self, character_id: UUID, version: int) -> CharacterCard: ...
    async def add_state(self, character: Character) -> None: ...
    async def save_state(self, character: Character, expected_version: int) -> Character: ...


class PartyRepository(Protocol):
    async def get(self, member_id: UUID) -> PartyMember: ...
    async def list_for_world(self, world_id: UUID) -> list[PartyMember]: ...
    async def find_by_name(self, world_id: UUID, name_key: str) -> PartyMember | None: ...
    async def add(self, member: PartyMember) -> None: ...
    async def save_sheet(
        self, member_id: UUID, sheet: Sheet, expected_version: int
    ) -> PartyMember: ...


class PhaseRepository(Protocol):
    async def create_run(self, run: PhaseRun) -> None: ...
    async def get_run(self, run_id: UUID) -> PhaseRun: ...
    async def find_open_run(self, world_id: UUID) -> PhaseRun | None: ...
    async def set_run_state(self, run_id: UUID, state: str) -> None: ...
    async def add_snapshot(self, snapshot: PhaseSnapshot) -> None: ...
    async def get_snapshot(self, snapshot_id: UUID) -> PhaseSnapshot: ...


class EventRepository(Protocol):
    async def max_sequence(self, world_id: UUID) -> int: ...
    async def append_event(self, event: WorldEvent) -> None: ...
    async def append_effect(self, effect: CommittedEffect) -> None: ...
    async def get_event(self, event_id: UUID) -> WorldEvent: ...
    async def find_by_phase_run(self, world_id: UUID, phase_run_id: UUID) -> WorldEvent | None: ...
    async def list_effects(self, event_id: UUID) -> list[CommittedEffect]: ...
    async def list_range(self, world_id: UUID, after: int, limit: int) -> list[WorldEvent]: ...
    async def count_events(self, world_id: UUID) -> int: ...


class CommandRepository(Protocol):
    async def get_by_key(self, world_id: UUID, key: str) -> UUID | None: ...
    async def get_input_hash(self, command_id: UUID) -> str: ...
    async def get_result(self, command_id: UUID) -> UUID | None: ...
    async def add(
        self,
        command_id: UUID,
        world_id: UUID,
        key: str,
        actor_role: str,
        command_type: str,
        expected_versions: dict[str, int],
        payload: dict[str, object],
        input_hash: str,
    ) -> None: ...
    async def set_result(self, command_id: UUID, event_id: UUID) -> None: ...


class VersionStore(Protocol):
    async def get(self, aggregate_id: UUID) -> int | None: ...
    async def ensure(self, aggregate_id: UUID, world_id: UUID, kind: str) -> None: ...
    async def compare_and_bump(self, expected: dict[UUID, int]) -> dict[UUID, int]: ...


class TaskRepository(Protocol):
    async def create(
        self,
        task_id: UUID,
        world_id: UUID,
        kind: str,
        key: str,
        max_attempts: int = 3,
    ) -> TaskRun: ...
    async def get(self, task_id: UUID) -> TaskRun: ...
    async def find_by_key(self, world_id: UUID, key: str) -> TaskRun | None: ...
    async def claim(self, task_id: UUID, owner: str, lease: Lease) -> TaskRun | None: ...
    async def claim_due(
        self, kind: str | None, owner: str, lease_s: float, limit: int
    ) -> list[TaskRun]: ...
    async def heartbeat(self, task_id: UUID, owner: str, expires_at: datetime) -> bool: ...
    async def finish(self, task_id: UUID, owner: str, state: str) -> bool: ...
    async def fail(
        self, task_id: UUID, owner: str, state: str, expires_at: datetime | None
    ) -> bool: ...
    async def requeue_expired(self, now: datetime) -> int: ...


class OutboxRepository(Protocol):
    async def add(self, message: OutboxMessage) -> None: ...
    async def claim_due(self, limit: int) -> list[OutboxMessage]: ...
    async def ack(self, message_id: UUID) -> bool: ...
    async def fail(self, message_id: UUID) -> bool: ...
    async def count_pending(self, world_id: UUID) -> int: ...
    async def requeue_claimed(self) -> int: ...


class PerceptionRepository(Protocol):
    async def add_observation(self, observation: Observation) -> None: ...
    async def observations_for_event(self, event_id: UUID) -> list[Observation]: ...
    async def observations_for_observer(
        self, observer_id: UUID, limit: int = 20
    ) -> list[Observation]: ...
    async def add_memory(self, memory: RecentMemory) -> None: ...
    async def memories_for_owner(self, owner_id: UUID) -> list[RecentMemory]: ...


class SceneRepository(Protocol):
    """Stage 1 scene records, committed atomically with their event."""

    async def save_intent(self, intent: Intent) -> None: ...
    async def save_scene(self, scene: Scene, event_id: UUID) -> None: ...
    async def save_attempt(self, attempt: Attempt) -> None: ...
    async def save_reaction(self, reaction: Reaction) -> None: ...
    async def save_resolution(self, resolution: Resolution) -> None: ...
    async def save_narration(self, beat: NarrationBeat) -> None: ...
    async def get_intent(self, intent_id: UUID) -> Intent: ...
    async def get_scene(self, scene_id: UUID) -> Scene: ...
    async def get_attempt(self, attempt_id: UUID) -> Attempt: ...
    async def get_resolution(self, scene_id: UUID) -> Resolution: ...
    async def narrations_for_event(self, event_id: UUID) -> list[NarrationBeat]: ...
    async def list_for_run(self, phase_run_id: UUID, limit: int = 50) -> list[Scene]: ...
    async def reactions_for_scene(self, scene_id: UUID) -> list[Reaction]: ...
