"""Repository ports for Stage 0 aggregates (owned by S0-UOW-001).

Adapters return domain models, never ORM objects. Every mutating save
compares an expected optimistic version and bumps on success.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from worldsim.domain.activities import Activity, TravelRoute
from worldsim.domain.characters import Character, CharacterCard
from worldsim.domain.costs import ModelCost
from worldsim.domain.events import CommittedEffect, WorldEvent
from worldsim.domain.knowledge import Belief, Claim
from worldsim.domain.macro import MacroAggregateEffect, MacroInterruption, MacroPeriodRun
from worldsim.domain.memory import MemoryDigest
from worldsim.domain.narration import NarrationBeat
from worldsim.domain.narrative import NarrativeArc, NarrativeHook
from worldsim.domain.party import Monster, PartyMember
from worldsim.domain.perception import Observation, RecentMemory
from worldsim.domain.phases import PhaseRun, PhaseSnapshot
from worldsim.domain.progress import CharacterSkill, ItemInstance, SkillDefinition, TrainingSession
from worldsim.domain.relationships import Relationship, RelationshipEvidence
from worldsim.domain.roles import RoleGrant
from worldsim.domain.rules.dnd import Sheet
from worldsim.domain.scenes import Attempt, Intent, Reaction, Resolution, Scene
from worldsim.domain.schedules import ScheduledEffect
from worldsim.domain.summaries import DailySummary
from worldsim.domain.tasks import Lease, OutboxMessage, TaskRun
from worldsim.domain.world import Location, World


def canonical_order(ids: list[UUID]) -> list[UUID]:
    """Deterministic lock order: every transaction locks shared aggregates
    cheapest-first by ID hex, so two writers cannot deadlock."""
    return sorted(set(ids), key=lambda item: item.hex)


class WorldRepository(Protocol):
    async def get(self, world_id: UUID) -> World: ...
    async def list_worlds(self) -> list[World]: ...
    async def add(self, world: World) -> None: ...
    async def save(self, world: World, expected_version: int) -> World: ...
    async def get_clock(self, world_id: UUID) -> tuple[int, str, int]: ...
    async def set_clock(
        self, world_id: UUID, day: int, phase: str, absolute_index: int
    ) -> None: ...
    async def get_config(self, world_id: UUID) -> dict[str, object]: ...
    async def put_config(self, world_id: UUID, key: str, value: object) -> None: ...


class LocationRepository(Protocol):
    async def get(self, location_id: UUID) -> Location: ...
    async def list_for_world(self, world_id: UUID) -> list[Location]: ...
    async def add(self, location: Location) -> None: ...
    async def save(self, location: Location, expected_version: int) -> Location: ...


class CharacterRepository(Protocol):
    async def get(self, character_id: UUID) -> Character: ...
    async def list_for_world(self, world_id: UUID) -> list[Character]: ...
    async def add_identity(self, character_id: UUID, world_id: UUID, name: str) -> None: ...
    async def add_card(self, card: CharacterCard) -> None: ...
    async def get_card(self, character_id: UUID, version: int) -> CharacterCard: ...
    async def add_state(self, character: Character) -> None: ...
    async def save_state(self, character: Character, expected_version: int) -> Character: ...


class PartyRepository(Protocol):
    async def get(self, member_id: UUID) -> PartyMember: ...
    async def list_for_world(self, world_id: UUID) -> list[PartyMember]: ...
    async def find_by_name(self, world_id: UUID, name_key: str) -> PartyMember | None: ...
    async def add(self, member: PartyMember) -> None: ...
    async def save_sheet(
        self, member_id: UUID, sheet: Sheet, expected_version: int
    ) -> PartyMember: ...


class MonsterRepository(Protocol):
    async def list_for_world(self, world_id: UUID) -> list[Monster]: ...
    async def add(self, monster: Monster) -> None: ...
    async def save_hp(
        self, monster_id: UUID, hp_current: int, expected_version: int
    ) -> Monster: ...


class ActivityRepository(Protocol):
    async def get(self, activity_id: UUID) -> Activity: ...
    async def list_active_for_world(self, world_id: UUID) -> list[Activity]: ...
    async def list_for_character(self, world_id: UUID, character_id: UUID) -> list[Activity]: ...
    async def add(self, activity: Activity) -> None: ...
    async def save(self, activity: Activity, expected_version: int) -> Activity: ...


class RouteRepository(Protocol):
    async def list_for_world(self, world_id: UUID) -> list[TravelRoute]: ...
    async def add(self, route: TravelRoute) -> None: ...
    async def save(self, route: TravelRoute, expected_version: int) -> TravelRoute: ...
    async def remove(self, route_id: UUID) -> None: ...


class ScheduleRepository(Protocol):
    async def add(self, schedule: ScheduledEffect) -> None: ...
    async def list_due(self, world_id: UUID, absolute: int) -> list[ScheduledEffect]: ...
    async def save(self, schedule: ScheduledEffect, expected_version: int) -> ScheduledEffect: ...


class RelationshipRepository(Protocol):
    async def add_evidence(self, evidence: RelationshipEvidence) -> None: ...
    async def get_pair(
        self, world_id: UUID, source_id: UUID, target_id: UUID
    ) -> Relationship | None: ...
    async def list_for_character(
        self, world_id: UUID, character_id: UUID
    ) -> list[Relationship]: ...
    async def add_relationship(self, relationship: Relationship) -> None: ...
    async def save_relationship(
        self, relationship: Relationship, expected_version: int
    ) -> Relationship: ...
    async def get_relationship(self, relationship_id: UUID) -> Relationship: ...


class KnowledgeRepository(Protocol):
    async def add_claim(self, claim: Claim) -> None: ...
    async def get_claim(self, claim_id: UUID) -> Claim: ...
    async def list_claims_for_world(self, world_id: UUID) -> list[Claim]: ...
    async def get_belief(
        self, world_id: UUID, holder_id: UUID, proposition: str
    ) -> Belief | None: ...
    async def list_beliefs_for_holder(self, world_id: UUID, holder_id: UUID) -> list[Belief]: ...
    async def add_belief(self, belief: Belief) -> None: ...
    async def save_belief(self, belief: Belief, expected_version: int) -> Belief: ...
    async def get_belief_by_id(self, belief_id: UUID) -> Belief: ...


class ProgressRepository(Protocol):
    async def ensure_skill(
        self, world_id: UUID, skill_key: str, name: str | None = None
    ) -> SkillDefinition: ...
    async def get_skill(
        self, world_id: UUID, character_id: UUID, skill_key: str
    ) -> CharacterSkill | None: ...
    async def list_skills_for_character(
        self, world_id: UUID, character_id: UUID
    ) -> list[CharacterSkill]: ...
    async def add_skill(self, skill: CharacterSkill) -> None: ...
    async def save_skill(self, skill: CharacterSkill, expected_version: int) -> CharacterSkill: ...
    async def has_session(
        self, world_id: UUID, character_id: UUID, skill_key: str, session_key: str
    ) -> bool: ...
    async def add_session(self, session: TrainingSession) -> None: ...


class InventoryRepository(Protocol):
    async def get_item(self, item_id: UUID) -> ItemInstance: ...
    async def list_for_owner(self, world_id: UUID, owner_id: UUID | None) -> list[ItemInstance]: ...
    async def add_item(self, item: ItemInstance) -> None: ...
    async def save_item(self, item: ItemInstance, expected_version: int) -> ItemInstance: ...
    async def remove_item(self, item_id: UUID) -> None: ...


class NarrativeRepository(Protocol):
    async def add_hook(self, hook: NarrativeHook) -> None: ...
    async def add_arc(self, arc: NarrativeArc) -> None: ...
    async def count_active_hooks(self, world_id: UUID) -> int: ...
    async def count_active_arcs(self, world_id: UUID) -> int: ...
    async def list_hooks_for_world(self, world_id: UUID) -> list[NarrativeHook]: ...
    async def list_arcs_for_world(self, world_id: UUID) -> list[NarrativeArc]: ...
    async def get_hook(self, hook_id: UUID) -> NarrativeHook: ...
    async def get_arc(self, arc_id: UUID) -> NarrativeArc: ...


class SummaryRepository(Protocol):
    async def add(self, summary: DailySummary) -> None: ...
    async def count_versions(self, world_id: UUID, owner_id: UUID, day: int) -> int: ...
    async def list_for_owner(self, world_id: UUID, owner_id: UUID) -> list[DailySummary]: ...


class DigestRepository(Protocol):
    async def add(self, digest: MemoryDigest) -> None: ...
    async def count_versions(self, world_id: UUID, owner_id: UUID, day: int) -> int: ...
    async def list_for_owner(self, world_id: UUID, owner_id: UUID) -> list[MemoryDigest]: ...


class CostRepository(Protocol):
    async def add(self, cost: ModelCost, world_id: UUID | None) -> None: ...
    async def get_for_call(self, call_id: UUID) -> ModelCost | None: ...
    async def total_for_world(self, world_id: UUID) -> float: ...


class RoleRepository(Protocol):
    async def get_for_world(self, world_id: UUID) -> RoleGrant | None: ...
    async def set_grant(self, grant: RoleGrant) -> RoleGrant: ...


class PhaseRepository(Protocol):
    async def create_run(self, run: PhaseRun) -> None: ...
    async def get_run(self, run_id: UUID) -> PhaseRun: ...
    async def find_open_run(self, world_id: UUID) -> PhaseRun | None: ...
    async def latest_run(self, world_id: UUID) -> PhaseRun | None: ...
    async def set_run_state(self, run_id: UUID, state: str) -> None: ...
    async def add_snapshot(self, snapshot: PhaseSnapshot) -> None: ...
    async def get_snapshot(self, snapshot_id: UUID) -> PhaseSnapshot: ...


class EventRepository(Protocol):
    async def max_sequence(self, world_id: UUID) -> int: ...
    async def append_event(self, event: WorldEvent) -> None: ...
    async def append_effect(self, effect: CommittedEffect) -> None: ...
    async def get_event(self, event_id: UUID) -> WorldEvent: ...
    async def find_by_phase_run(self, world_id: UUID, phase_run_id: UUID) -> WorldEvent | None: ...
    async def list_effects(self, event_id: UUID) -> list[CommittedEffect]: ...
    async def list_range(self, world_id: UUID, after: int, limit: int) -> list[WorldEvent]: ...
    async def count_events(self, world_id: UUID) -> int: ...


class CommandRepository(Protocol):
    async def get_by_key(self, world_id: UUID, key: str) -> UUID | None: ...
    async def get_input_hash(self, command_id: UUID) -> str: ...
    async def get_result(self, command_id: UUID) -> UUID | None: ...
    async def add(
        self,
        command_id: UUID,
        world_id: UUID,
        key: str,
        actor_role: str,
        command_type: str,
        expected_versions: dict[str, int],
        payload: dict[str, object],
        input_hash: str,
    ) -> None: ...
    async def set_result(self, command_id: UUID, event_id: UUID) -> None: ...


class VersionStore(Protocol):
    async def get(self, aggregate_id: UUID) -> int | None: ...
    async def ensure(self, aggregate_id: UUID, world_id: UUID, kind: str) -> None: ...
    async def compare_and_bump(self, expected: dict[UUID, int]) -> dict[UUID, int]: ...
    async def check(self, expected: dict[UUID, int]) -> None: ...


class TaskRepository(Protocol):
    async def create(
        self,
        task_id: UUID,
        world_id: UUID,
        kind: str,
        key: str,
        max_attempts: int = 3,
    ) -> TaskRun: ...
    async def get(self, task_id: UUID) -> TaskRun: ...
    async def find_by_key(self, world_id: UUID, key: str) -> TaskRun | None: ...
    async def claim(self, task_id: UUID, owner: str, lease: Lease) -> TaskRun | None: ...
    async def claim_due(
        self, kind: str | None, owner: str, lease_s: float, limit: int
    ) -> list[TaskRun]: ...
    async def heartbeat(self, task_id: UUID, owner: str, expires_at: datetime) -> bool: ...
    async def finish(self, task_id: UUID, owner: str, state: str) -> bool: ...
    async def fail(
        self, task_id: UUID, owner: str, state: str, expires_at: datetime | None
    ) -> bool: ...
    async def requeue_expired(self, now: datetime) -> int: ...


class OutboxRepository(Protocol):
    async def add(self, message: OutboxMessage) -> None: ...
    async def claim_due(self, limit: int) -> list[OutboxMessage]: ...
    async def ack(self, message_id: UUID) -> bool: ...
    async def fail(self, message_id: UUID) -> bool: ...
    async def count_pending(self, world_id: UUID) -> int: ...
    async def requeue_claimed(self) -> int: ...


class PerceptionRepository(Protocol):
    async def add_observation(self, observation: Observation) -> None: ...
    async def observations_for_event(self, event_id: UUID) -> list[Observation]: ...
    async def observations_for_observer(
        self,
        observer_id: UUID,
        limit: int = 20,
        since_phase_index: int = 0,
        min_salience: float = 0.0,
    ) -> list[Observation]: ...
    async def add_memory(self, memory: RecentMemory) -> None: ...
    async def memories_for_owner(
        self, owner_id: UUID, since_phase_index: int = 0, min_salience: float = 0.0
    ) -> list[RecentMemory]: ...
    async def bump_salience(
        self,
        observation_ids: list[UUID],
        memory_ids: list[UUID],
        amount: float,
        cap: float,
    ) -> None: ...


class SceneRepository(Protocol):
    """Stage 1 scene records, committed atomically with their event."""

    async def save_intent(self, intent: Intent) -> None: ...
    async def save_scene(self, scene: Scene, event_id: UUID) -> None: ...
    async def save_attempt(self, attempt: Attempt) -> None: ...
    async def save_reaction(self, reaction: Reaction) -> None: ...
    async def save_resolution(self, resolution: Resolution) -> None: ...
    async def save_narration(self, beat: NarrationBeat) -> None: ...
    async def get_intent(self, intent_id: UUID) -> Intent: ...
    async def get_scene(self, scene_id: UUID) -> Scene: ...
    async def get_attempt(self, attempt_id: UUID) -> Attempt: ...
    async def get_resolution(self, scene_id: UUID) -> Resolution: ...
    async def narrations_for_event(self, event_id: UUID) -> list[NarrationBeat]: ...
    async def list_for_run(self, phase_run_id: UUID, limit: int = 50) -> list[Scene]: ...
    async def reactions_for_scene(self, scene_id: UUID) -> list[Reaction]: ...


class MacroRepository(Protocol):
    """Stage 5 macro runs, aggregate effects, and interruptions."""

    async def get_run(self, run_id: UUID) -> MacroPeriodRun: ...
    async def create_run(self, run: MacroPeriodRun) -> None: ...
    async def save_run(self, run: MacroPeriodRun, expected_version: int) -> MacroPeriodRun: ...
    async def add_effect(self, effect: MacroAggregateEffect) -> None: ...
    async def list_effects(self, run_id: UUID) -> list[MacroAggregateEffect]: ...
    async def add_interruption(self, interruption: MacroInterruption) -> None: ...
    async def list_interruptions(self, run_id: UUID) -> list[MacroInterruption]: ...
